app:
  domain: http://localhost:8080
sendgrid:
  api_key:
  api_host: http://localhost:3030
  delivery_method: sendgrid
  raise_delivery_errors: true
mail:
  from: dev-no-replay@find-market.jp
sakura:
  domain: find-market.sakura.ne.jp
  user: dev-no-replay@find-market.jp
  password: find39ml

