app:
  host: http://localhost:3000
sendgrid:
  api_key:
  api_host: http://localhost:3030
  delivery_method: sendgrid
  raise_delivery_errors: true
  default_url_options:
    host: localhost:3000
mail:
  from: dev-no-replay@find-market.jp
sakura:
  domain: find-market.sakura.ne.jp
  user: dev-no-replay@find-market.jp
  password: find39ml
