require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/AssignmentInCondition:
  Enambled: false


Rails/DynamicFindBy:
  Whitelist:
    - find_by_id
